[package]
name = "quick_swap"
version = "0.1.0"
authors = ["manthanmabc <manthanmji@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.5.1"